# Generated by Django 3.2.18 on 2023-02-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gündem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(max_length=80, verbose_name='Başlık')),
                ('metin', models.TextField(max_length=200, verbose_name='metin')),
                ('Tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı bilgisi',
                'ordering': ['-Tarih'],
            },
        ),
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslık', models.CharField(max_length=80, verbose_name='Haber başlığı')),
                ('Haber_Detay', models.TextField(max_length=5000, verbose_name='haber detayları')),
                ('anasayfa_resm', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Anasayfa Kayar Kısımda Görüntülenecek Fotoğrafı Yükleyiniz"/static/img/xxx.xx"Biçim')),
                ('resm1', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"Biçim')),
                ('resm12', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"Biçim')),
                ('resm13', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"Biçim')),
                ('resm14', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"Biçim')),
                ('resm15', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"Biçim')),
                ('Görüntüleme', models.IntegerField(verbose_name='Görüntüleme')),
                ('HaberTur', models.CharField(choices=[('Ekonomi', 'Ekonomi'), ('İslam', 'İslam'), ('Savaş', 'Savaş'), ('Teknoloji', 'Teknoloji'), ('Gündelik', 'Gündelik'), ('Dünya', 'Dünya'), ('OrtaDoğu', 'OrtaDoğu')], default='İslam', max_length=50)),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haberler',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='İşHaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=50, verbose_name='İş Başlığı')),
                ('newsDetail', models.TextField(max_length=5000, verbose_name='İş Detayları')),
                ('imgShow', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='İş sorgulama sayfasını gösteren resim')),
                ('upLoadImg', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"格式')),
                ('upLoadImg2', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"格式')),
                ('upLoadImg3', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"格式')),
                ('upLoadImg4', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"格式')),
                ('upLoadImg5', models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Haberdeki resmi yükleyin, lütfen referans resmi kullanın"/static/img/xxx.xx"格式')),
                ('viewedTimes', models.IntegerField(verbose_name='Görüntüleme')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İş danışmanlığı',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='KayanHaberler1EnustSag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(max_length=50, verbose_name='Başlık')),
                ('resim', models.FileField(null=True, upload_to='img/')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='bağlantı adresi (boş olabilir)')),
                ('önyazi', models.CharField(blank=True, max_length=500, null=True, verbose_name='altyazı')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kayan Haberler 1 En Üst Sağ',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='KayanHaberler1Enustsol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(max_length=50, verbose_name='Başlık')),
                ('resim', models.FileField(null=True, upload_to='img/')),
                ('Linkto', models.CharField(blank=True, max_length=50, verbose_name='bağlantı adresi (boş olabilir)')),
                ('önyazi', models.CharField(blank=True, max_length=500, null=True, verbose_name='altyazı')),
                ('dimDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kayan Haberler 1 En Üst Sol',
                'ordering': ['-dimDate'],
            },
        ),
        migrations.CreateModel(
            name='Kullanıcı',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kullanıcı_adı', models.CharField(max_length=50, verbose_name='Kullanıcı adı')),
                ('parola', models.CharField(max_length=50, verbose_name='parola')),
                ('mail', models.EmailField(max_length=500, verbose_name='e-posta')),
            ],
            options={
                'verbose_name': 'Kullanıcı bilgisi',
            },
        ),
        migrations.CreateModel(
            name='SonDakikaHBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(max_length=80, verbose_name='Başlık')),
                ('Fotograf1', models.FileField(blank=True, null=True, upload_to='img/SonDakika/', verbose_name='Birinci Fotoğraf')),
                ('FotoğrafArasıMetin', models.TextField(max_length=200, null=True, verbose_name='FotoğrafArasıMetin')),
                ('Fotograf2', models.FileField(blank=True, null=True, upload_to='img/SonDakika/', verbose_name='İkinci fotoğraf Fotoğraf')),
                ('FotoğrafArasıMetin2', models.TextField(max_length=200, null=True, verbose_name='FotoğrafArasıMetin')),
                ('Fotograf3', models.FileField(blank=True, null=True, upload_to='img/SonDakika/', verbose_name='Üçüncü Fotoğraf Fotoğraf')),
                ('metin', models.TextField(max_length=200, verbose_name='metin')),
                ('Tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Son Dakika',
                'ordering': ['-Tarih'],
            },
        ),
        migrations.CreateModel(
            name='TarihteBugun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.CharField(max_length=100, verbose_name='Baslik')),
                ('OnYazı', models.TextField(max_length=5000, verbose_name='ÖnYazı')),
                ('Araresim', models.FileField(blank=True, null=True, upload_to='img/araresim/', verbose_name='Araresim')),
                ('Yazı', models.TextField(max_length=9000, verbose_name='AsılMetin')),
                ('Yayıntarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarihte Bugün',
                'ordering': ['-Yayıntarih'],
            },
        ),
    ]
